# Generated by Django 4.2 on 2023-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_class_year_alter_subject_subject_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classasignment',
            constraint=models.UniqueConstraint(fields=('class_id', 'subject_id'), name='unique_classroom_subject'),
        ),
    ]
